// Single source of truth for SEO metadata, structured data, robots and
// sitemap. Keep the NAP (name / address / phone) here in sync with the
// footer, contact section and Google Business Profile — search engines
// cross-check them.

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://www.muggleship.com"
).replace(/\/+$/, "");

export const SITE_NAME = "MuggleShip";

export const SITE_TITLE = "FBA Prep & eCommerce Fulfillment UK | MuggleShip";

export const SITE_DESCRIPTION =
  "UK FBA prep, eCommerce fulfillment and cross-border shipping from our Bedford warehouse, plus Amazon price automation, analytics and listing optimization. Get a free quote.";

// Generated by src/app/og.png/route.tsx.
export const OG_IMAGE = {
  url: "/og.png",
  width: 1200,
  height: 630,
  alt: "MuggleShip — FBA Prep & eCommerce Fulfillment from the UK",
};

export const CONTACT = {
  email: "support@muggleship.com",
  phone: "+44 7931 580067",
  phoneE164: "+447931580067",
};

export const ADDRESSES = {
  london: {
    streetAddress: "86-90 Paul Street",
    addressLocality: "London",
    postalCode: "EC2A 4NE",
    addressCountry: "GB",
  },
  bedford: {
    streetAddress: "Unit 2, Caxton Road",
    addressLocality: "Bedford",
    postalCode: "MK41 0LF",
    addressCountry: "GB",
  },
};

export const SERVICES = [
  { id: "fba-prep", name: "FBA Prep", description: "FNSKU labeling, poly bagging, palletization and direct-to-Amazon dispatch from the UK." },
  { id: "fulfillment", name: "eCommerce Fulfillment", description: "Pick, pack and ship for Shopify, eBay, Walmart, WooCommerce and BigCommerce orders." },
  { id: "cross-border", name: "Cross-Border Shipping", description: "DDP shipping, customs clearance and multi-marketplace dispatch." },
  { id: "returns", name: "Returns Management", description: "End-to-end RMA handling with restock or disposal and same-day processing." },
  { id: "automated-pricing", name: "Amazon Price Automation", description: "Rule-based price updates via Amazon SP-API using the seller's own margin and pricing rules." },
  { id: "analytics", name: "Amazon Analytics & Reporting", description: "Inventory health, fulfillment SLA, sales velocity and restock reporting." },
  { id: "listing-optimization", name: "Amazon Listing Optimization", description: "Listing creation, A+ content, keyword research and image optimization." },
  { id: "buyer-messaging", name: "Buyer-Seller Messaging", description: "Order enquiries, dispatch updates and returns correspondence handled on the seller's behalf." },
];

// Pages listed in sitemap.xml. Update lastModified when a page's content
// materially changes.
export const PAGES = [
  { path: "/", lastModified: "2026-10-01", changeFrequency: "monthly", priority: 1 },
  { path: "/privacy/", lastModified: "2026-10-01", changeFrequency: "yearly", priority: 0.3 },
  { path: "/terms/", lastModified: "2026-04-28", changeFrequency: "yearly", priority: 0.3 },
] as const;
